<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class invoice_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

    public function getAdmin($id){
        $this->db->where('id_admin', $id);
        return $this->db->get('admin');
    }

    public function getBarangByCart($id){
        $this->db->where('id_cart', $id);
        $this->db->from('orders');
        $this->db->join('product', 'orders.id_product = product.id_product');
        return $this->db->get()->result();
    }

    public function getBarangById($id){
        $this->db->select('*');
        $this->db->from('orders');
        $this->db->join('product', 'product.id_product = orders.id_product');
        $this->db->where('id_orders', $id);
        $result = $this->db->get();

        if ($result->num_rows() > 0) {
            foreach ($result->result() as $a) {
              $data = array(
                'id_orders' => $a->id_orders,
                'quantity'  => $a->quantity,
                'name'      => $a->name,
              );
            }
        }
        return $data;
    }
}

/* End of file Payment_model.php */
/* Location: ./application/models/Payment_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-11 05:32:38 */
/* http://harviacode.com */
