<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Product_model extends CI_Model
{

    public $table = 'product';
    public $id = 'id_product';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($id=null)
    {
        $this->db->order_by($this->id, $this->order);
        if($id!=null){
          $this->db->where('id_admin', $id);
          return $this->db->get($this->table)->result();

        }else{
          return $this->db->get($this->table)->result();
        }
    }

    //get field
    function get_field(){
      return $this->db->list_fields($this->table);
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_product', $q);
	$this->db->or_like('code_product', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('size', $q);
	$this->db->or_like('url_photo', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('stock', $q);
	$this->db->or_like('id_category', $q);
	$this->db->or_like('id_admin', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_product', $q);
	$this->db->or_like('code_product', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('size', $q);
	$this->db->or_like('url_photo', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('stock', $q);
	$this->db->or_like('id_category', $q);
	$this->db->or_like('id_admin', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function boolInsert($data){//sama seperti fungsi insert namun memakai return value untuk menentukan berhasil atau tidak
      $this->db->insert($this->table, $data);
      if ($this->db->affected_rows()>0) {
     return true;
     }else{
     return false;
     }
    }

    function getId(){//mengambil id_product terbaru
    $this->db->order_by('id_product', 'DESC');
    $db=$this->db->get($this->table)->row();
    return $db;
  }
    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

     function getadm($idadm){
        $this->db->where($this->id_admin,$idadm);
        return $this->db->get($this->admin)->row();
    }

    function getctr($idctr){
        $this->db->where($this->id_category,$idctr);
        return $this->db->get($this->category)->row();
    }
}

/* End of file Product_model.php */
/* Location: ./application/models/Product_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-26 00:56:54 */
/* http://harviacode.com */
