<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Chatbot_model extends CI_Model
{

    public $table = 'chatbot';
    public $id = 'id_chatbot';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    //get field
    function get_field(){
      return $this->db->list_fields($this->table);
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_chatbot', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('access_token', $q);
	$this->db->or_like('secret_token', $q);
	$this->db->or_like('expire_token', $q);
	$this->db->or_like('id_admin', $q);
	$this->db->or_like('id_superadmin', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_chatbot', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('access_token', $q);
	$this->db->or_like('secret_token', $q);
	$this->db->or_like('expire_token', $q);
	$this->db->or_like('id_admin', $q);
	$this->db->or_like('id_superadmin', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Chatbot_model.php */
/* Location: ./application/models/Chatbot_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-26 02:36:22 */
/* http://harviacode.com */